//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class QuestionaireEntities : DbContext
{
    public QuestionaireEntities()
        : base("name=QuestionaireEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Answers> Answers { get; set; }
    public DbSet<AnswersForm> AnswersForm { get; set; }
    public DbSet<Questions> Questions { get; set; }
    public DbSet<QuestionsForms> QuestionsForms { get; set; }
    public DbSet<Users> Users { get; set; }
}
